<h1>Simple Output Template</h1>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at libero id ante gravida pulvinar. Vestibulum feugiat ipsum elit. In vel convallis ipsum. Pellentesque ac odio efficitur, pulvinar metus aliquet, mollis eros. Nulla efficitur tincidunt auctor. Integer sit amet est at sem venenatis sagittis id ac sem. Ut a mi non orci placerat venenatis. Fusce in lectus iaculis, rhoncus urna pharetra, feugiat elit. Aliquam vel tempor purus, tincidunt vulputate sapien. Vivamus tincidunt ipsum turpis, quis ornare libero rhoncus in. 
</p>

<?php print $this->render("copyright"); ?>